---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos_7
    image: centos:7
    pre_build_image: true
  - name: centos_8
    image: centos:8_update
    pre_build_image: true
  - name: ubuntu
    image: ubuntu:python
    pre_build_image: true
  - name: instance
    image: quay.io/centos/centos:stream8
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
